#!/bin/sh
echo "# Auto-generated Actions list"
echo
echo `date`
echo
echo "for branch=$(git branch | sed -n -e 's/^\* \(.*\)/\1/p')"
echo

echo "# Methods"
grep " def " actions.py | grep -v "^#" | sed -e 's/ def //' | sed -e 's/self//' | sed -e 's/(, /(/' | sed -e 's/()//' | sed -e 's/\(.*\)/  *\1/' | sed -e 's/://' | sort -n \
	| grep -v "parserlist\|check_if_should_start_openframeworks\|create_serial_port_process\|__init__\|persist_composite_setting\|receive_detour_info\|_refresh_frame_buffer\|refresh_frame_buffer_and_restart_openframeworks\|run_script\|setup_osc_server\|start_confirm_action\|stop_serial_port_process\|stop_openframeworks_process\|update_capture_settings\|update_config_settings\|update_video_settings\|try_remove_file\|get_callback\|call_method_name\|call_parse_method\|detect_types"
echo

echo "## Dynamic routes"
grep '( r"' actions.py | sed -e 's/\(.*\)"\(.*\)"\(.*\)/  * \2/'  | sed -e 's/\$//' | sed -e 's/\^//'
echo

echo "### Plugin routes"
grep "( r\"" plugins/*.py | sed -e 's/plugins\/\(.*\)\.py:\(.*\)\( r\"\)\(.*\)\"\(.*\)/  * \4\t(from \1)/' | grep -v "open_serial" | sed -e 's/\$//' | sed -e 's/\^//'
echo 

echo "----"
echo
echo "Autogenerated by dotfiles/generate-list-actions.sh"

