#!/bin/sh
echo "====== Auto-generated Actions list ======\n"
echo `date`
echo
echo "for branch=$(git branch | sed -n -e 's/^\* \(.*\)/\1/p')"
echo
echo

echo "===== Methods ====="
grep " def " actions.py | grep -v "^#" | sed -e 's/ def //' | sed -e 's/self//' | sed -e 's/(, /(/' | sed -e 's/()//' | sed -e 's/\(.*\)/  *\1/' | sort -n

echo -e "\n\n===== Dynamic routes ====="
grep '( r"' actions.py | sed -e 's/\(.*\)"\(.*\)"\(.*\)/  * \2/p'


echo -e "\n----\n"
echo "Autogenerated by dotfiles/generate-list-actions.sh"
